### ISSUE TITLE
Diagramy PU

### ISSUE THREAD

**Issue by j-markiewicz** [j-markiewicz/IO#8]
Wersja wstępna, niewiadomo czy o to chodziło: [[Klient]-(Zaloguj się do systemu), [Administracja]-(Zaloguj się do systemu), [Kurier]-(Zaloguj się do systemu), [Klient]-(Nadaj Paczkę), [Klient]-(Odbierz Paczkę), [Klient]-(Śledź paczkę), [Klient]-(Zmień datę odbioru), [Klient]-(Złóż zażalenie), [Klient]-(Kontakt z kurierem), [Klient]-(Zmień sposób dostarczenia lub adres), [Kurier]-(Odczytaj obszar pracy), [Kurier]-(Odczytaj tryb pracy), [Kurier]-(Odczytaj przydzielone auto), [Kurier]-(Zmień Status Paczki), [Kurier]-(Kontakt z klientem), [Administracja]-(Kontakt z klientem), [Administracja]-(Przydziel zadania Kurierom), [Administracja]-(Rozpatrz zażalenie)](https://yuml.me/diagram/plain/usecase/[Klient]-(Zaloguj%20si%C4%99%20do%20systemu),%20[Administracja]-(Zaloguj%20si%C4%99%20do%20systemu),%20[Kurier]-(Zaloguj%20si%C4%99%20do%20systemu),%20[Klient]-(Nadaj%20Paczk%C4%99),%20[Klient]-(Odbierz%20Paczk%C4%99),%20[Klient]-(%C5%9Aled%C5%BA%20paczk%C4%99),%20[Klient]-(Zmie%C5%84%20dat%C4%99%20odbioru),%20[Klient]-(Z%C5%82%C3%B3%C5%BC%20za%C5%BCalenie),%20[Klient]-(Kontakt%20z%20kurierem),%20[Klient]-(Zmie%C5%84%20spos%C3%B3b%20dostarczenia%20lub%20adres),%20[Kurier]-(Odczytaj%20obszar%20pracy),%20[Kurier]-(Odczytaj%20tryb%20pracy),%20[Kurier]-(Odczytaj%20przydzielone%20auto),%20[Kurier]-(Zmie%C5%84%20Status%20Paczki),%20[Kurier]-(Kontakt%20z%20klientem),%20[Administracja]-(Kontakt%20z%20klientem),%20[Administracja]-(Przydziel%20zadania%20Kurierom),%20[Administracja]-(Rozpatrz%20za%C5%BCalenie)).

![diagram](https://yuml.me/diagram/plain/usecase/[Klient]-(Zaloguj%20si%C4%99%20do%20systemu),%20[Administracja]-(Zaloguj%20si%C4%99%20do%20systemu),%20[Kurier]-(Zaloguj%20si%C4%99%20do%20systemu),%20[Klient]-(Nadaj%20Paczk%C4%99),%20[Klient]-(Odbierz%20Paczk%C4%99),%20[Klient]-(%C5%9Aled%C5%BA%20paczk%C4%99),%20[Klient]-(Zmie%C5%84%20dat%C4%99%20odbioru),%20[Klient]-(Z%C5%82%C3%B3%C5%BC%20za%C5%BCalenie),%20[Klient]-(Kontakt%20z%20kurierem),%20[Klient]-(Zmie%C5%84%20spos%C3%B3b%20dostarczenia%20lub%20adres),%20[Kurier]-(Odczytaj%20obszar%20pracy),%20[Kurier]-(Odczytaj%20tryb%20pracy),%20[Kurier]-(Odczytaj%20przydzielone%20auto),%20[Kurier]-(Zmie%C5%84%20Status%20Paczki),%20[Kurier]-(Kontakt%20z%20klientem),%20[Administracja]-(Kontakt%20z%20klientem),%20[Administracja]-(Przydziel%20zadania%20Kurierom),%20[Administracja]-(Rozpatrz%20za%C5%BCalenie))

**Comment by MarysiaR2023** [comment]
Wg ćwiczen wyglada że jest w porzadku. Można usunąć zaloguj się do systemu bo jest to przypadek pomocniczy

**Comment by j-markiewicz** [comment]
Czyli taki [[Klient]-(Nadaj Paczkę), [Klient]-(Odbierz Paczkę), [Klient]-(Śledź paczkę), [Klient]-(Zmień datę odbioru), [Klient]-(Złóż zażalenie), [Klient]-(Kontakt z kurierem), [Klient]-(Zmień sposób dostarczenia lub adres), [Kurier]-(Odczytaj obszar pracy), [Kurier]-(Odczytaj tryb pracy), [Kurier]-(Odczytaj przydzielone auto), [Kurier]-(Zmień Status Paczki), [Kurier]-(Kontakt z klientem), [Administracja]-(Kontakt z klientem), [Administracja]-(Przydziel zadania Kurierom), [Administracja]-(Rozpatrz zażalenie)](https://yuml.me/diagram/plain/usecase/[Klient]-(Nadaj%20Paczk%C4%99),%20[Klient]-(Odbierz%20Paczk%C4%99),%20[Klient]-(%C5%9Aled%C5%BA%20paczk%C4%99),%20[Klient]-(Zmie%C5%84%20dat%C4%99%20odbioru),%20[Klient]-(Z%C5%82%C3%B3%C5%BC%20za%C5%BCalenie),%20[Klient]-(Kontakt%20z%20kurierem),%20[Klient]-(Zmie%C5%84%20spos%C3%B3b%20dostarczenia%20lub%20adres),%20[Kurier]-(Odczytaj%20obszar%20pracy),%20[Kurier]-(Odczytaj%20tryb%20pracy),%20[Kurier]-(Odczytaj%20przydzielone%20auto),%20[Kurier]-(Zmie%C5%84%20Status%20Paczki),%20[Kurier]-(Kontakt%20z%20klientem),%20[Administracja]-(Kontakt%20z%20klientem),%20[Administracja]-(Przydziel%20zadania%20Kurierom),%20[Administracja]-(Rozpatrz%20za%C5%BCalenie))?

![](https://yuml.me/diagram/plain/usecase/[Klient]-(Nadaj%20Paczk%C4%99),%20[Klient]-(Odbierz%20Paczk%C4%99),%20[Klient]-(%C5%9Aled%C5%BA%20paczk%C4%99),%20[Klient]-(Zmie%C5%84%20dat%C4%99%20odbioru),%20[Klient]-(Z%C5%82%C3%B3%C5%BC%20za%C5%BCalenie),%20[Klient]-(Kontakt%20z%20kurierem),%20[Klient]-(Zmie%C5%84%20spos%C3%B3b%20dostarczenia%20lub%20adres),%20[Kurier]-(Odczytaj%20obszar%20pracy),%20[Kurier]-(Odczytaj%20tryb%20pracy),%20[Kurier]-(Odczytaj%20przydzielone%20auto),%20[Kurier]-(Zmie%C5%84%20Status%20Paczki),%20[Kurier]-(Kontakt%20z%20klientem),%20[Administracja]-(Kontakt%20z%20klientem),%20[Administracja]-(Przydziel%20zadania%20Kurierom),%20[Administracja]-(Rozpatrz%20za%C5%BCalenie))

**Comment by MarysiaR2023** [comment]
Chyba tak trzeba to przekonwertowac do pdf i wyslac

**Comment by j-markiewicz** [comment]
Wysłane na redminie [IO-diagram.pdf](https://github.com/j-markiewicz/IO/files/13619744/IO-diagram.pdf).
